const dbConnection = require("../mongoConnection");
const data = require("../data/");
const books = data.book;

async function main() {
  const db = await dbConnection();
  await db.dropDatabase();

  //HarryPotter
  const harry1 = await books.create("Harry Potter And The Sorcerer's Stone", "J.K. Rowling","Scholastic Press","Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3009-9","uploads/harry1.png","Used Book","English","1998-08-31","HARRY POTTER");
  const harry2 = await books.create("Harry Potter And The Chamber of Secrets", "J.K. Rowling","Scholastic Press","Harry Potter and the Chamber of Secrets is a fantasy novel written by British author J. K. Rowling and the second novel in the Harry Potter series. The plot follows Harry's second year at Hogwarts School of Witchcraft and Wizardry, during which a series of messages on the walls of the school's corridors warn that the \"Chamber of Secrets\" has been opened and that the \"heir of Slytherin\" would kill all pupils who do not come from all-magical families. These threats are found after attacks which leave residents of the school petrified. Throughout the year, Harry and his friends Ron and Hermione investigate the attacks.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3010-9","uploads/harry2.png","Used Book","English","1999-06-02","HARRY POTTER");
  const harry3 = await books.create("Harry Potter And The Prisoner of Azkaban", "J.K. Rowling","Scholastic Press","Harry Potter and the Prisoner of Azkaban is a fantasy novel written by British author J. K. Rowling and the third in the Harry Potter series. The book follows Harry Potter, a young wizard, in his third year at Hogwarts School of Witchcraft and Wizardry. Along with friends Ronald Weasley and Hermione Granger, Harry investigates Sirius Black, an escaped prisoner from Azkaban who they believe is one of Lord Voldemort's old allies.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3011-9","uploads/harry3.png","Used Book","English","1999-09-08","HARRY POTTER");
  const harry4 = await books.create("Harry Potter And The Goblet of Fire", "J.K. Rowling","Scholastic Press","Harry Potter and the Goblet of Fire is a fantasy book written by British author J. K. Rowling and the fourth novel in the Harry Potter series. It follows Harry Potter, a wizard in his fourth year at Hogwarts School of Witchcraft and Wizardry and the mystery surrounding the entry of Harry's name into the Triwizard Tournament, in which he is forced to compete.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3012-9","uploads/harry4.png","Used Book","English","2000-07-08","HARRY POTTER");
  const harry5 = await books.create("Harry Potter And The Order of the Phoenix", "J.K. Rowling","Scholastic Press","Harry Potter and the Order of the Phoenix is a fantasy novel written by British author J. K. Rowling and the fifth novel in the Harry Potter series. It follows Harry Potter's struggles through his fifth year at Hogwarts School of Witchcraft and Wizardry, including the surreptitious return of the antagonist Lord Voldemort, O.W.L. exams, and an obstructive Ministry of Magic. The novel was published on 21 June 2003 by Bloomsbury in the United Kingdom, Scholastic in the United States, and Raincoast in Canada. Five million copies were sold in the first 24 hours of publication.[1] It is the longest book of the series.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3013-9","uploads/harry5.png","Used Book","English","2003-06-21","HARRY POTTER");
  const harry6 = await books.create("Harry Potter And The Half-Blood Prince", "J.K. Rowling","Scholastic Press","Harry Potter and the Half-Blood Prince is a fantasy novel written by British author J. K. Rowling and the sixth and penultimate novel in the Harry Potter series. Set during protagonist Harry Potter's sixth year at Hogwarts, the novel explores the past of Harry's nemesis, Lord Voldemort, and Harry's preparations for the final battle against Voldemort alongside his headmaster and mentor Albus Dumbledore.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3014-9","uploads/harry6.png","Used Book","English","2005-07-16","HARRY POTTER");
  const harry7 = await books.create("Harry Potter And The Deathly Hallows", "J.K. Rowling","Scholastic Press","Harry Potter and the Deathly Hallows is a fantasy novel written by British author J. K. Rowling and the seventh and final novel of the Harry Potter series. The book was released on 21 July 2007, ending the series that began in 1997 with the publication of Harry Potter and the Philosopher's Stone. It was published in the United Kingdom by Bloomsbury Publishing, in the United States by Scholastic, and in Canada by Raincoast Books. The novel chronicles the events directly following Harry Potter and the Half-Blood Prince (2005) and the final confrontation between the wizards Harry Potter and Lord Voldemort.",["Fiction", "Fanasy","Drama","Thriller"],"3.79","0-7475-3015-9","uploads/harry7.png","Used Book","English","2007-07-21","HARRY POTTER");


  //NightSide no.3
  const nightside1 = await books.create("Something from the Nightside", "Simon R. Green","Ace","Taylor is the name, John Taylor. My card says I’m a detective, but what I really am is an expert on finding lost things. It’s part of the gift I was born with as a child of the Nightside.\n\nI left there a long time ago, with my skin and sanity barely intact. Now I make my living in the sunlit streets of London. But business has been slow lately, so when Joanna Barrett showed up at my door, reeking of wealth, asking me to find her runaway teenage daughter, I didn’t say no.",["Science Fiction ", "Supernatural"],"10.79","0-440-01319-4","uploads/night1.png","Used Book","English","2003-05-27","NIGHTSIDE");
  const nightside2 = await books.create("Agents of Light and Darkness", "Simon R. Green","Ace","John Taylor works in the Nightside—the gaudy, neon noir, secret heart of London, where it’s always three in the morning, where gods and monsters make deals and seek pleasures they won’t find anywhere else. He has a gift for finding things. And sometimes what he's hired to locate can be very, very dangerous indeed.",["Science Fiction ", "Supernatural"],"10.79","0-441-01319-5","uploads/night2.png","Used Book","English","2003-10-28","NIGHTSIDE");
  const nightside3 = await books.create("Nightingale's Lament", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Science Fiction ", "Supernatural"],"10.79","0-441-01319-6","uploads/night3.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside4 = await books.create("Hex and the City", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Science Fiction ", "Supernatural"],"10.79","0-441-01319-7","uploads/night4.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside5 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Science Fiction ", "Supernatural"],"10.79","0-441-01319-8","uploads/night5.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside6 = await books.create("Sharper than a Serpent's Tooth", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Science Fiction ", "Supernatural"],"10.79","0-441-01319-8","uploads/night6.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside7 = await books.create("Hell to Pay", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Science Fiction ", "Supernatural"],"10.79","0-441-01319-8","uploads/night7.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside8 = await books.create("The Unnatural Inquirer", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Science Fiction ", "Supernatural"],"10.79","0-441-01319-8","uploads/night8.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside9 = await books.create("Just Another Judgement Day", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Science Fiction ", "Supernatural"],"10.79","0-441-01319-8","uploads/night9.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside10 = await books.create("The Good, the Bad, and the Uncanny", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Science Fiction ", "Supernatural"],"10.79","0-441-01319-8","uploads/night10.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside11 = await books.create("A Hard Day's Knight", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Science Fiction ", "Supernatural"],"10.79","0-441-01319-8","uploads/night11.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const nightside12 = await books.create("The Bride Wore Black Leather", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Science Fiction ", "Supernatural"],"10.79","0-441-01319-8","uploads/night12.png","Used Book","English","2005-08-30","NIGHTSIDE");
 
  //Hunger
  const hunger1 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-8","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const hunger2 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-8","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const hunger3 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-8","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");

  //Ice and fire
  const ice1 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-8","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const ice2 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-8","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const ice3 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-8","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const ice4 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-8","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const ice5 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-8","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const ice6 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-8","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");
  const ice7 = await books.create("Paths not Taken", "Simon R. Green","Ace","John Taylor is the name. I work the Nightside. Only in that dark heart of London where it’s always three A.M., where human and inhuman can feed their darkest desires, do I feel at home. Probably because I was born there.",["Fiction", "Fanasy","Drama","Thriller"],"10.79","0-441-01319-8","uploads/night1.png","Used Book","English","2005-08-30","NIGHTSIDE");


  console.log("Done seeding database");
  await db.close();
}

main();